//! Fixture-backed tests for every `CalibrationError` variant, plus the
//! read-only/no-WAL-sidecar guarantee documented in `src/sql.rs`.
//!
//! The malformed fixtures are generated by `tests/fixtures/generate.py`;
//! see that file for what each one deliberately gets wrong.

use std::path::Path;

use timsrust_calibration::{sql::read_all, CalibrationError, RunCalibration};

#[test]
fn null_not_null_mz_column_errors() {
    let err = read_all("tests/fixtures/null_mz_field.d/analysis.tdf").unwrap_err();
    match err {
        CalibrationError::UnexpectedNull { table, column } => {
            assert_eq!(table, "MzCalibration");
            assert_eq!(column, "DigitizerTimebase");
        }
        other => panic!("expected UnexpectedNull, got {other:?}"),
    }
}

#[test]
fn null_not_null_frame_column_errors() {
    let err = read_all("tests/fixtures/null_frame_t1.d/analysis.tdf").unwrap_err();
    match err {
        CalibrationError::UnexpectedNull { table, column } => {
            assert_eq!(table, "Frames");
            assert_eq!(column, "T1");
        }
        other => panic!("expected UnexpectedNull, got {other:?}"),
    }
}

#[test]
fn missing_mz_coefficients_errors() {
    // C0/C1 are schema-nullable, so the read itself succeeds; the error
    // only surfaces once a converter is actually requested.
    let run = RunCalibration::from_path("tests/fixtures/missing_mz_coeffs.d/analysis.tdf")
        .expect("read_all should succeed: C0 is schema-nullable");
    let err = run.mz_converter_median().unwrap_err();
    assert!(
        matches!(err, CalibrationError::MissingMzCoefficients(1)),
        "expected MissingMzCoefficients(1), got {err:?}"
    );
}

#[test]
fn missing_im_coefficients_errors() {
    let run = RunCalibration::from_path("tests/fixtures/missing_im_coeffs.d/analysis.tdf")
        .expect("read_all should succeed: C6 is schema-nullable");
    let err = run.im_converter_median().unwrap_err();
    assert!(
        matches!(err, CalibrationError::MissingImCoefficients(2)),
        "expected MissingImCoefficients(2), got {err:?}"
    );
}

#[test]
fn unsupported_mz_model_errors() {
    let run = RunCalibration::from_path("tests/fixtures/bad_mz_model.d/analysis.tdf").unwrap();
    let err = run.mz_converter_median().unwrap_err();
    assert!(
        matches!(err, CalibrationError::UnsupportedMzModel(99)),
        "expected UnsupportedMzModel(99), got {err:?}"
    );
}

#[test]
fn unsupported_im_model_errors() {
    let run = RunCalibration::from_path("tests/fixtures/bad_im_model.d/analysis.tdf").unwrap();
    let err = run.im_converter_median().unwrap_err();
    assert!(
        matches!(err, CalibrationError::UnsupportedImModel(99)),
        "expected UnsupportedImModel(99), got {err:?}"
    );
}

#[test]
fn dangling_cal_id_errors() {
    // Frames.MzCalibration points at id 999, which has no matching
    // MzCalibration row.
    let run = RunCalibration::from_path("tests/fixtures/bad_cal_id.d/analysis.tdf").unwrap();
    let err = run.mz_converter_median().unwrap_err();
    assert!(
        matches!(err, CalibrationError::CalIdNotFound(999)),
        "expected CalIdNotFound(999), got {err:?}"
    );
}

#[test]
fn unknown_frame_id_errors() {
    let run = RunCalibration::from_path("tests/fixtures/flat_t1.d/analysis.tdf").unwrap();
    let err = run.mz_converter(9999).unwrap_err();
    assert!(
        matches!(err, CalibrationError::FrameNotFound(9999)),
        "expected FrameNotFound(9999), got {err:?}"
    );
}

/// The module doc on `src/sql.rs` claims a read-only open never creates a
/// `-wal`/`-shm` sidecar next to the `.tdf` file. Verify it against a real
/// fixture rather than just trusting the source comment.
#[test]
fn read_only_open_leaves_no_wal_sidecar() {
    let tdf = Path::new("tests/fixtures/flat_t1.d/analysis.tdf");
    let wal = tdf.with_extension("tdf-wal");
    let shm = tdf.with_extension("tdf-shm");
    // Clean up any stray sidecar from a previous failed run before asserting.
    let _ = std::fs::remove_file(&wal);
    let _ = std::fs::remove_file(&shm);

    read_all(tdf).unwrap();

    assert!(
        !wal.exists(),
        "read-only open must not create a -wal sidecar at {}",
        wal.display()
    );
    assert!(
        !shm.exists(),
        "read-only open must not create a -shm sidecar at {}",
        shm.display()
    );
}
